package net.sf.RecordEditor.layoutEd.Table;

import net.sf.RecordEditor.utils.jdbc.AbsRecord;

/**
 *   This class holds the fields extracted from a SQL statement:
 *
 *   <pre>
 *       Select TblKey, Details
 *       From   Tbl_TI_IntTbls
 *       Where  TblId = ?
 *       Order By TblKey
 *
 *   </pre>
 * This class also provides both specific field access methods
 * and Generic (based on Field number) access
 *
 * @Author Generated by BuildJava.Rexx by Bruce Martin
 *
 */
public final class TableRec extends AbsRecord {

  private int TblKey;
  protected int initTblKey ;
  private String Details;



  public TableRec () {
      super();

      TblKey = 0;
      Details = "";

      setKeys();
  }

  public TableRec (
                    int pTblKey
                  , String pDetails
                  ) {
      super(false);

      TblKey = pTblKey;
      Details = pDetails;

      setKeys();
  }


  /**
   *  This method copies the key fields to the Init* fields
   */
  public void setKeys() {

      initTblKey = TblKey;
  }

  


  /**
   * @see net.sf.RecordEditor.utils.jdbc.AbsRecord#hasTheKeyChanged()
   */
  @Override
  public boolean hasTheKeyChanged() {
	  return initTblKey != TblKey;
  }

/**
   *  This method returns clones the current record
   *
   *  @return a duplicate of the current record
   */
  public Object clone() {

      super.clone();

      TableRec ret = new TableRec(
                        TblKey
                      , Details
                    );

      ret.setNew(true);

      return ret;
  }



  /**
   *  This method returns clones the current record
   */
  public int getFieldCount() {
      return 2;
  }




  /**
   *  This method returns a field (specified by field number)
   *
   *  @param fieldNum the field number (in the record)
   *  @return the request field
   */
  public Object getField(int fieldNum) {

      if (updateStatus == NULL_INT_VALUE) return "";

      switch (fieldNum) {
        case (0) : return new Integer(TblKey);
        case (1) : return Details;
        default  : return "";
      }
  }


  /**
   *  This method sets a field (specified by field number) with a string value
   *
   *  @param fieldNum the field number (in the record)
   *  @param val the value to be assigned to the field
   */
  protected void setFieldWithString(int fieldNum, String val) {

      switch (fieldNum) {
        case (0) : setTblKey(cnvToInt(TblKey, val, "TblKey" ));
        break;
        case (1) : setDetails(val);
        break;
        default  : ;
      }
  }


  /**
   *  This method sets a field (specified by field number) with an object value
   *
   *  @param fieldNum the field number (in the record)
   *  @param val the value to be assigned to the field
   */
  protected void setFieldWithObject(int fieldNum, Object val) {

      switch (fieldNum) {
        case (0) : setTblKey(((Integer) val).intValue());
        break;
        default  : setFieldWithString(fieldNum, (String) val) ;
      }
  }

  /**
   *  This method gets the vaule of TblKey
   */
  public int getTblKey() {
      return TblKey;
  }

  /**
   *  This method sets the vaule of TblKey
   *
   * @param val value to be assigned to TblKey
   */
  public void setTblKey(int val) {

      if ((val != TblKey) || (updateStatus == NULL_INT_VALUE)) {
           TblKey = val;
           updateStatus = UPDATED;
      }
  }

  /**
   *  This method gets the vaule of Details
   */
  public String getDetails() {
      return Details;
  }

  /**
   *  This method sets the vaule of Details
   *
   * @param val value to be assigned to Details
   */
  public void setDetails(String val) {

      if ((val == null || "".equals(val))
      && (Details == null || "".equals(Details))) {
          return;
      }

      if ((val == null) || (! val.equals(Details)) || (updateStatus == NULL_INT_VALUE)) {
           Details = val;
           updateStatus = UPDATED;
      }
  }

}
